import './globals.css'
import { UserContextProvider } from './context/userStore'
import { ReceiverProvider } from './context/receiverStore'
import { ActiveChatIndexProvider } from './context/activeChatIndexStore'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <UserContextProvider>
          <ActiveChatIndexProvider>
            <ReceiverProvider>
              {children}
            </ReceiverProvider>
          </ActiveChatIndexProvider>
        </UserContextProvider>
      </body>
    </html>
  )
}
