import './globals.css'
import { GlobalChatProvider } from './context/store'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <GlobalChatProvider>
          {children}
        </GlobalChatProvider>
      </body>
    </html>
  )
}
